name: "Hing's Johor Real Estate"
favicon: null
layout_spectrum: 0.25337
typography_spectrum: 0.579
title: The Tech-savvy real estate agent in Johor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-42533698-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f7ec'
    - '#99a8a1'
    - '#24821d'
    - '#75bc15'
    - '#6a6b63'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.9836816482711583
  rhythmicContrast: 0.75
purpose: []
