name: "Hing's Johor Real Estate"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56936
title: The Tech-savvy real estate agent in Johor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-42533698-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010508'
    - '#fffa01'
    - '#90b7a4'
    - '#f30050'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.9836816482711583
  rhythmicContrast: 0.75
purpose: []
