name: "Hing's Johor Real Estate"
favicon: null
layout_spectrum: 0.62399
typography_spectrum: 0.49495
title: The Tech-savvy real estate agent in Johor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-42533698-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#69c7eb'
    - '#2e302b'
    - '#000000'
    - '#015fb0'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
